# Generated by Django 4.1.6 on 2023-02-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raspisanie', '0003_rename_image_raspisanie_raspisanie_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raspisanie',
            options={'ordering': ('id',), 'verbose_name': 'Сабактардын жугуртмосу ', 'verbose_name_plural': 'Сабактардын жугуртмосу '},
        ),
    ]
