# Generated by Django 4.1.6 on 2023-02-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('id',), 'verbose_name': 'Жанылыктар', 'verbose_name_plural': 'Жанылыктар'},
        ),
    ]
