# Generated by Django 4.1.6 on 2023-02-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('id',), 'verbose_name': 'Акыркы Кабарлар', 'verbose_name_plural': 'Акыркы Кабарлар'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('id',), 'verbose_name': 'Контакттар', 'verbose_name_plural': 'Контакттар'},
        ),
    ]
