# Generated by Django 4.1.6 on 2023-02-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_makal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ('id',), 'verbose_name': 'Биз жонундо маалымат', 'verbose_name_plural': 'Биз жонундо кошумча маалыматтар'},
        ),
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ('id',), 'verbose_name': 'Биздин сабак', 'verbose_name_plural': 'Биздин сабактар'},
        ),
        migrations.AlterModelOptions(
            name='makal',
            options={'ordering': ('id',), 'verbose_name': 'Макалдар', 'verbose_name_plural': 'Макалдар'},
        ),
    ]
