# Generated by Django 4.1.6 on 2023-02-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlament', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parlament',
            options={'ordering': ('id',), 'verbose_name': 'Мектеп парламенти'},
        ),
    ]
