# Generated by Django 4.1.6 on 2023-02-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_remove_parents_desc_parents_parents_doc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parents',
            options={'ordering': ('id',), 'verbose_name': 'Ата энелерге!', 'verbose_name_plural': 'Ата эненлерге'},
        ),
    ]
