# Generated by Django 4.1.6 on 2023-02-15 10:41

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='About_image', verbose_name='Сурот'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to=255, verbose_name='Сурот'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_news',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='news_image/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='pride',
            name='image_pride',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image_pride/', verbose_name='Суроту!'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo_site',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo_site/', verbose_name='Мектептин логотиби'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='first_slide',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='slide_site/', verbose_name='Биринчи слайд'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='second_slide',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='slide_site/', verbose_name='Второй слайд'),
        ),
    ]
