# Generated by Django 4.1.6 on 2023-02-17 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_about_image_alter_certificate_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аты')),
            ],
            options={
                'verbose_name': 'Галерея ',
                'verbose_name_plural': 'Галерея',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='GalleryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(upload_to='gallery/', verbose_name='Сурот')),
                ('gallery_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='settings.gallery', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Галерея  болумго киргизуу',
                'verbose_name_plural': 'Галерея  болумго киргизуу',
                'ordering': ('id',),
            },
        ),
    ]
