# Generated by Django 4.1.6 on 2023-02-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_gallery_gallerydetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('id',), 'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
        migrations.AddField(
            model_name='gallery',
            name='gallery_image',
            field=models.ImageField(default=1, upload_to='gallery/', verbose_name='Сурот'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GalleryDetail',
        ),
    ]
