# Generated by Django 4.1.6 on 2023-02-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_data_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ('id',), 'verbose_name': 'Сертификаттар', 'verbose_name_plural': 'Сертификаттар'},
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ('id',), 'verbose_name': 'Биз сандабыз!', 'verbose_name_plural': 'Биз сандабыз!'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ('id',), 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайд'},
        ),
    ]
