# Generated by Django 4.1.6 on 2023-02-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achyk', '0002_rename_achyksaat_file_achyksaatdetail_achyksaat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achyksaat',
            options={'ordering': ('id',), 'verbose_name': 'Ачык саат', 'verbose_name_plural': 'Ачык саат'},
        ),
        migrations.AlterModelOptions(
            name='achyksaatdetail',
            options={'ordering': ('id',), 'verbose_name': 'Ачык саат болумго киргизуу', 'verbose_name_plural': 'Ачык саат болумго киргизуу'},
        ),
    ]
