# Generated by Django 4.1.6 on 2023-02-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallerydetail_accreditation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('id',), 'verbose_name': 'Галерея ', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='gallerydetail',
            options={'ordering': ('id',), 'verbose_name': 'Галерея  болумго киргизуу', 'verbose_name_plural': 'Галерея  болумго киргизуу'},
        ),
    ]
