# Generated by Django 4.1.6 on 2023-02-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prog_akred', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acreditationlist2',
            options={'ordering': ('id',), 'verbose_name': 'Программалык аккредитация', 'verbose_name_plural': 'Программалык аккредитация'},
        ),
        migrations.AlterModelOptions(
            name='acreditationlist2detail',
            options={'ordering': ('id',), 'verbose_name': 'Программалык аккредитация болумго киргизуу', 'verbose_name_plural': 'Программалык аккредитация болумго киргизуу'},
        ),
    ]
