# Generated by Django 4.1.6 on 2023-02-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pride',
            options={'ordering': ('id',), 'verbose_name': 'Сыймыктанабыз!', 'verbose_name_plural': 'Сыймыктанабыз!'},
        ),
    ]
